In [3]:
import numpy as np
word = np.array(['wo','shi','shei'])
mask = np.array([True,False,True])
word = word[mask]
print(word)

['wo' 'shei']


In [5]:
import torch
x = torch.Tensor([[2,1],[2,1]])
y = torch.Tensor([[2,2],[2,2]])
print(x)
print(y)
ans = x * y 
print(ans)

tensor([[2., 1.],
        [2., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[4., 2.],
        [4., 2.]])


In [16]:
import torch
import torch.nn.functional as F
a = torch.Tensor([[0,12,33],[55,12,0]]).to(torch.long)
print(a)
print(~(a == 0))
logit = F.one_hot(a.reshape(-1),num_classes = 56)

print(logit)

tensor([[ 0, 12, 33],
        [55, 12,  0]])
tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 

In [ ]:
depth_gt = 
tensor([[[[ 0.0000, 58.5141, 56.6080,  ..., 18.5802, 18.3594, 18.8663],
          [ 0.0000,  0.0000, 56.5780,  ..., 19.4065, 19.1745, 19.0249],
          [53.1410,  0.0000, 56.4987,  ..., 19.4660, 19.1756, 18.9399],
          ...,
          [ 7.1608,  7.2032,  6.3703,  ...,  1.9585,  1.8890,  1.8401],
          [ 6.2273,  6.3212,  5.7295,  ...,  0.0000,  0.0000,  0.0000],
          [ 5.5581,  5.6267,  5.1647,  ...,  1.8319,  1.8007,  1.7979]]
         
tensor([[[[-1.0000, 57.5141, 55.6080,  ..., 17.5802, 17.3594, 17.8663],
          [-1.0000, -1.0000, 55.5780,  ..., 18.4065, 18.1745, 18.0249],
          [52.1410, -1.0000, 55.4987,  ..., 18.4660, 18.1756, 17.9399],
          ...,
          [ 6.1608,  6.2032,  5.3703,  ...,  0.9585,  0.8890,  0.8401],
          [ 5.2273,  5.3212,  4.7295,  ..., -1.0000, -1.0000, -1.0000],
          [ 4.5581,  4.6267,  4.1647,  ...,  0.8319,  0.8007,  0.7979]],
         
tensor([[[[ 0, 57, 55,  ..., 17, 17, 17],
          [ 0,  0, 55,  ..., 18, 18, 18],
          [52,  0, 55,  ..., 18, 18, 17],